version: '3.8'
services:
  web:
    build:
      context: .
    command: gunicorn --bind 0.0.0.0:8000 locallibrary.wsgi --workers=4
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    expose:
      - "8000"
    networks:
      - django-network
  nginx:
    build: nginx
    restart: always
    volumes:
      - static_volume:/usr/src/app/static
      - media_volume:/usr/src/app/media
    ports:
      - "80:80"
    depends_on:
      - web
    networks:
      - django-network
networks:
  django-network:
    name: django-network
volumes:
  media_volume:
  static_volume: